use std::error::Error;

pub async fn do_something() -> Result<(), Box<dyn Error>> {
    Ok(())
}
